var ua = require('./user_agent');

const properties = {
  'azimuth': {initial: 'center', inherit: true},
  'background-attachment': {initial: 'scroll'},
  'background-color': {initial: 'transparent'},
  'background-image': {initial: 'none'},
  'background-position': {initial: '0% 0%'},
  'background-repeat': {initial: 'repeat'},
  'border-collapse': {initial: 'separate', inherit: true},
  "border-style": {inherit: false},
  "border-spacing": {initial: 0, inherit: true},
  'border-top-color': {initial: ua.color},
  'border-right-color': {initial: ua.color},
  'border-bottom-color': {initial: ua.color},
  'border-left-color': {initial: ua.color},
  'border-top-width': {initial: 'medium'},
  'border-right-width': {initial:'medium' },
  'border-bottom-width': {initial: 'medium'},
  'border-left-color': {initial: 'medium'},
  'bottom': {initial: 'auto'},
  'caption-side': {initial: 'top', inherit: true},
  'clear': {initial: 'none'},
  'clip': {initial: 'auto'},
  "color": {initial: ua.color, inherit: true},
  'content': {initial: 'normal'},
  'cursor': {initial: 'auto' },
  'direction': {initial: 'ltr', inherit: true },
  'display': {initial: 'inline'},
  'float': {initial: 'none'},
  'font-family': {inherit: true},
  'font-size': {initial: 'medium', inherit: true},
  'font-style': {initial: 'normal', inherit: true},
  'font-variant': {initial: 'normal', inherit: true},
  'font-weight': {initial: 'normal', inherit: true},
  'height': {initial: 'auto'},
  'left': {initial: 'auto'},
  'letter-spacing': {initial: 'normal', inherit: true},
  'line-height': {initial: 'normal', inherit: true},
  'list-style-image': {initial: 'none', inherit: true},
  'list-style-position': {initial: 'outside', inherit: true},
  'list-style-type': {initial: 'disc', inherit: true},
  'margin-right': {initial: 0},
  'margin-left': {initial: 0},
  'margin-top': {initial: 0},
  'margin-bottom': {initial: 0},
  'max-height': {initial: 'none'},
  'max-width': {initial: 'none'},
  'min-height': {initial: 0},
  'min-width': {initial: 0},
  'orphans': {initial: 2, inherit: true},
  'outline-color': {initial: 'invert'},
  'outline-stye': {initial: 'none'},
  'outline-width': {initial: 'medium'},
  'overflow': {initial: 'visible'},
  'padding-top': {initial: 0},
  'padding-bottom': {initial: 0},
  'padding-left': {initial: 0},
  'padding-right': {initial: 0},
  'position': {initial: 'static'},
  'right': {initial: 'auto'},
  'table-layout': {initial: 'auto'},
  'text-align': {initial: 'ltr', inherit: true}, // not exactly right - changes based on dir
  'text-decoration': {initial: 'none'},
  'text-indent': {initial: 0},
  'text-transform': {initial: 'none'},
  'top': {initial: 'auto'},
  'vertical-align': {initial: 'baseline'},
  'visibility': {initial: 'visible', inherit: true},
  'white-space': {initial: 'normal', inherit: true},
  'widows': {initial: 2, inherit: true},
  'width': {initial: 'auto'},
  'word-spacing': {initial: 'normal', inherit: true},
  'z-index': {initial: 'auto'}
};

module.exports = properties;
